import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { ReactNode } from 'react';

import { Footer } from '#src/components/common/footer/footer';
import { Header } from '#src/components/common/header/header';

import '../styles/globals.css';
import '../styles/reset.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const metadata: Metadata = {
  title: 'Artem Khvostyk',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export { metadata };
export default RootLayout;
